apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: email-dev
  labels:
    name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      name: http
    - port: 433
      nodePort: 30443
      name: https
  selector:
    app: nginxpod