---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcdappkust
  namespace: email-dev
spec:
  interval: 30s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcdapp
