---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcdapp
  namespace: email-dev
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/avinash3105/fluxcdapp.git